var searchData=
[
  ['mainviewmodel_0',['MainViewModel',['../class_music_player_m_v_v_m_1_1_view_models_1_1_main_view_model.html',1,'MusicPlayerMVVM.ViewModels.MainViewModel'],['../class_music_player_m_v_v_m_1_1_view_models_1_1_main_view_model.html#add916e85a622794a064f25ad33d555de',1,'MusicPlayerMVVM.ViewModels.MainViewModel.MainViewModel()']]],
  ['mainviewmodel_2ecs_1',['MainViewModel.cs',['../_main_view_model_8cs.html',1,'']]],
  ['mainwindow_2',['MainWindow',['../class_music_player_m_v_v_m_1_1_views_1_1_main_window.html',1,'MusicPlayerMVVM.Views.MainWindow'],['../class_music_player_m_v_v_m_1_1_views_1_1_main_window.html#addc375492a9b047a1c4eeb59f146e7b4',1,'MusicPlayerMVVM.Views.MainWindow.MainWindow()']]],
  ['mainwindow_2examl_2ecs_3',['MainWindow.xaml.cs',['../_main_window_8xaml_8cs.html',1,'']]],
  ['musicdbcontext_4',['MusicDbContext',['../class_music_player_m_v_v_m_1_1_data_1_1_music_db_context.html',1,'MusicPlayerMVVM.Data.MusicDbContext'],['../class_music_player_m_v_v_m_1_1_data_1_1_music_db_context.html#ad59a701d82afdd1a8da1691a08f4831c',1,'MusicPlayerMVVM.Data.MusicDbContext.MusicDbContext()']]],
  ['musicdbcontext_2ecs_5',['MusicDbContext.cs',['../_music_db_context_8cs.html',1,'']]],
  ['musicdbcontextmodelsnapshot_6',['MusicDbContextModelSnapshot',['../class_music_player_m_v_v_m_1_1_migrations_1_1_music_db_context_model_snapshot.html',1,'MusicPlayerMVVM::Migrations']]],
  ['musicdbcontextmodelsnapshot_2ecs_7',['MusicDbContextModelSnapshot.cs',['../_music_db_context_model_snapshot_8cs.html',1,'']]],
  ['musicplayer_8',['MusicPlayer',['../class_music_player_m_v_v_m_1_1_models_1_1_music_player.html',1,'MusicPlayerMVVM.Models.MusicPlayer'],['../class_music_player_m_v_v_m_1_1_models_1_1_music_player.html#af885a5454f4bb4f729e1468e02024654',1,'MusicPlayerMVVM.Models.MusicPlayer.MusicPlayer()']]],
  ['musicplayer_2ecs_9',['MusicPlayer.cs',['../_music_player_8cs.html',1,'']]],
  ['musicplayermvvm_10',['MusicPlayerMVVM',['../namespace_music_player_m_v_v_m.html',1,'']]],
  ['musicplayermvvm_3a_3acommon_11',['Common',['../namespace_music_player_m_v_v_m_1_1_common.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3adata_12',['Data',['../namespace_music_player_m_v_v_m_1_1_data.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3aevents_13',['Events',['../namespace_music_player_m_v_v_m_1_1_events.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3amigrations_14',['Migrations',['../namespace_music_player_m_v_v_m_1_1_migrations.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3amodels_15',['Models',['../namespace_music_player_m_v_v_m_1_1_models.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3aproperties_16',['Properties',['../namespace_music_player_m_v_v_m_1_1_properties.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3aviewmodels_17',['ViewModels',['../namespace_music_player_m_v_v_m_1_1_view_models.html',1,'MusicPlayerMVVM']]],
  ['musicplayermvvm_3a_3aviews_18',['Views',['../namespace_music_player_m_v_v_m_1_1_views.html',1,'MusicPlayerMVVM']]]
];
